name: gmaps_by_road_distance_calculator
description: This is a Package to calculate the by-road distance from one point to another in Gmap.
version: 2.0.2
homepage: "https://github.com/abinvs-2019/gmaps_distance_find_package"

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.1.2
